adding models and setup for tests
WelcomeToTheDjango/VotaExpress pull request #2
Opened 2024-01-27 00:15 UTC by keinermendoza

First step bro 🚀

2024-01-27 15:06 UTC, LopesLs commented
Precisa adicionar conteúdo no arquivo `.gitignore` para bloquear de subir cache para o repositório

2024-01-27 15:17 UTC, LopesLs requested changes
Precisa deletar esses arquivos de pycache e o banco de dados do github

2024-01-27 15:17 UTC, LopesLs commented on config/settings.py
Nunca subir a SECRET_KEY para o GitHub

2024-01-27 15:17 UTC, LopesLs commented on db.sqlite3
Não subir o banco de dados para o Github

2024-01-27 15:31 UTC, LopesLs approved these changes

2024-01-27 15:31 UTC, LopesLs commented on db.sqlite3
Resolvido!

2024-01-27 15:51 UTC, merged

2024-01-30 02:26 UTC, JonathanEsteves commented on config/settings.py
Verdade, para prezar a segurança da aplicação.